In [21]:
import numpy as np

In [22]:
environment_rows = 4
environment_columns = 6

rewards = np.full((environment_rows, environment_columns), 0.)
rewards[1, 5] = 1. #goal state

rewards[3,4] = -1 #trap position
rewards[3,5] = -1

for row in rewards:
    print(row)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0. -1. -1.]


In [23]:
def valid_actions(matrix, current_point):
    re = []
    rows = len(matrix)
    cols = len(matrix[0])
    if current_point[1]+1 < cols and matrix[current_point[0]][current_point[1]+1] != 1:
        re.append('right')
    if current_point[0] + 1 < rows and matrix[current_point[0]+1][current_point[1]] != 1:
        re.append('down')
    if current_point[1]-1 >=0 and matrix[current_point[0]][current_point[1]-1] != 1:
        re.append('left')
    if current_point[0]-1 >=0 and matrix[current_point[0]-1][current_point[1]] !=1:
        re.append('up')
    return re

In [24]:
def robot_move(current_point, action):
    if action == 'right':
        return (current_point[0], current_point[1]+1)
    if action == 'down':
        return (current_point[0]+1, current_point[1])
    if action == 'left':
        return (current_point[0], current_point[1]-1)
    if action == 'up':
        return (current_point[0]-1, current_point[1])

In [74]:
def main(matrix, start_point, end_point):
    queue = []
    step = 0
    current_point = start_point
    queue.append((current_point, [start_point]))
    matrix[current_point[0]][current_point[1]] = 1

    while queue:
        cur_point, cur_path = queue.pop(0)
        if cur_point == end_point:
            return cur_path
        else:
            acts = valid_actions(matrix, cur_point)
            if acts: # 如果有路可走
                for a in acts:
                    next_point = robot_move(cur_point, a)
                    queue.append((next_point, cur_path + [next_point]))  
                    matrix[next_point[0]][next_point[1]] = 1  

In [75]:
if __name__ == '__main__':
    Matrix = [[0,0,0,0,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,1,1]]
    start_point = (0, 0)
    end_point = (1, 5)
    shortest_path = main(Matrix, start_point, end_point)
    print(shortest_path)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5)]
